# Generated by Django 5.1.3 on 2024-11-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience', models.PositiveIntegerField()),
                ('min_ctc', models.PositiveIntegerField()),
                ('max_ctc', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('key_skills', models.JSONField()),
                ('job_type', models.CharField(max_length=50)),
                ('employment_type', models.CharField(max_length=50)),
                ('industry_type', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('candidates_needed', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter')),
            ],
        ),
    ]
